TARGETS=H2_1.0_OPT_0.1_mu_0.00025_sigmu0.25_10regions_ages.db \
H2_1.0_OPT_0.1_mu_0.00025_sigmu0.25_10regions_cumVG.db \
H2_1.0_OPT_0.1_mu_0.00025_sigmu0.25_10regions_popgen_fixations.db \
H2_1.0_OPT_0.1_mu_0.00025_sigmu0.25_10regions_popgen.db \
H2_1.0_OPT_0.1_mu_0.00025_sigmu0.25_10regions_stats.db \
H2_1.0_OPT_0.1_mu_0.00025_sigmu0.25_load.db \
H2_1.0_OPT_0.1_mu_0.00025_sigmu0.25_stats.db \
H2_1.0_OPT_0.1_mu_0.001_sigmu0.25_10regions_ages.db \
H2_1.0_OPT_0.1_mu_0.001_sigmu0.25_10regions_cumVG.db \
H2_1.0_OPT_0.1_mu_0.001_sigmu0.25_10regions_popgen_fixations.db \
H2_1.0_OPT_0.1_mu_0.001_sigmu0.25_10regions_popgen.db \
H2_1.0_OPT_0.1_mu_0.001_sigmu0.25_10regions_stats.db \
H2_1.0_OPT_0.1_mu_0.001_sigmu0.25_load.db \
H2_1.0_OPT_0.1_mu_0.001_sigmu0.25_stats.db \
H2_1.0_OPT_0.1_mu_0.005_sigmu0.25_10regions_ages.db \
H2_1.0_OPT_0.1_mu_0.005_sigmu0.25_10regions_cumVG.db \
H2_1.0_OPT_0.1_mu_0.005_sigmu0.25_10regions_popgen_fixations.db \
H2_1.0_OPT_0.1_mu_0.005_sigmu0.25_10regions_popgen.db \
H2_1.0_OPT_0.1_mu_0.005_sigmu0.25_10regions_stats.db \
H2_1.0_OPT_0.1_mu_0.005_sigmu0.25_load.db \
H2_1.0_OPT_0.1_mu_0.005_sigmu0.25_stats.db \
H2_1.0_OPT_0.5_mu_0.00025_sigmu0.25_10regions_ages.db \
H2_1.0_OPT_0.5_mu_0.00025_sigmu0.25_10regions_cumVG.db \
H2_1.0_OPT_0.5_mu_0.00025_sigmu0.25_10regions_popgen_fixations.db \
H2_1.0_OPT_0.5_mu_0.00025_sigmu0.25_10regions_popgen.db \
H2_1.0_OPT_0.5_mu_0.00025_sigmu0.25_10regions_stats.db \
H2_1.0_OPT_0.5_mu_0.00025_sigmu0.25_load.db \
H2_1.0_OPT_0.5_mu_0.00025_sigmu0.25_stats.db \
H2_1.0_OPT_0.5_mu_0.001_sigmu0.25_10regions_ages.db \
H2_1.0_OPT_0.5_mu_0.001_sigmu0.25_10regions_cumVG.db \
H2_1.0_OPT_0.5_mu_0.001_sigmu0.25_10regions_popgen_fixations.db \
H2_1.0_OPT_0.5_mu_0.001_sigmu0.25_10regions_popgen.db \
H2_1.0_OPT_0.5_mu_0.001_sigmu0.25_10regions_stats.db \
H2_1.0_OPT_0.5_mu_0.001_sigmu0.25_load.db \
H2_1.0_OPT_0.5_mu_0.001_sigmu0.25_stats.db \
H2_1.0_OPT_0.5_mu_0.005_sigmu0.25_10regions_ages.db \
H2_1.0_OPT_0.5_mu_0.005_sigmu0.25_10regions_cumVG.db \
H2_1.0_OPT_0.5_mu_0.005_sigmu0.25_10regions_popgen_fixations.db \
H2_1.0_OPT_0.5_mu_0.005_sigmu0.25_10regions_popgen.db \
H2_1.0_OPT_0.5_mu_0.005_sigmu0.25_10regions_stats.db \
H2_1.0_OPT_0.5_mu_0.005_sigmu0.25_load.db \
H2_1.0_OPT_0.5_mu_0.005_sigmu0.25_stats.db \
H2_1.0_OPT_1_mu_0.00025_sigmu0.25_10regions_ages.db \
H2_1.0_OPT_1_mu_0.00025_sigmu0.25_10regions_cumVG.db \
H2_1.0_OPT_1_mu_0.00025_sigmu0.25_10regions_popgen_fixations.db \
H2_1.0_OPT_1_mu_0.00025_sigmu0.25_10regions_popgen.db \
H2_1.0_OPT_1_mu_0.00025_sigmu0.25_10regions_stats.db \
H2_1.0_OPT_1_mu_0.00025_sigmu0.25_load.db \
H2_1.0_OPT_1_mu_0.00025_sigmu0.25_stats.db \
H2_1.0_OPT_1_mu_0.001_sigmu0.25_10regions_ages.db \
H2_1.0_OPT_1_mu_0.001_sigmu0.25_10regions_cumVG.db \
H2_1.0_OPT_1_mu_0.001_sigmu0.25_10regions_popgen_fixations.db \
H2_1.0_OPT_1_mu_0.001_sigmu0.25_10regions_popgen.db \
H2_1.0_OPT_1_mu_0.001_sigmu0.25_10regions_stats.db \
H2_1.0_OPT_1_mu_0.001_sigmu0.25_load.db \
H2_1.0_OPT_1_mu_0.001_sigmu0.25_stats.db \
H2_1.0_OPT_1_mu_0.005_sigmu0.25_10regions_ages.db \
H2_1.0_OPT_1_mu_0.005_sigmu0.25_10regions_cumVG.db \
H2_1.0_OPT_1_mu_0.005_sigmu0.25_10regions_popgen_fixations.db \
H2_1.0_OPT_1_mu_0.005_sigmu0.25_10regions_popgen.db \
H2_1.0_OPT_1_mu_0.005_sigmu0.25_10regions_stats.db \
H2_1.0_OPT_1_mu_0.005_sigmu0.25_load.db \
H2_1.0_OPT_1_mu_0.005_sigmu0.25_stats.db \
validation_popstats.db \
validation_skew.db


all: $(TARGETS)

%.db: ../%.h5
	python python/todb.py $< $@

clean: 
	rm -f $(TARGETS)
