%_per_locus.gz: ../%.db
	./summarise_10locus_popgen_per_locus.R -i $< -o $@

all: combined_10locus_popgen_per_locus.gz

combined_10locus_popgen_per_locus.gz: H2_1.0_OPT_0.1_mu_0.00025_sigmu0.25_10regions_popgen_per_locus.gz \
H2_1.0_OPT_0.1_mu_0.001_sigmu0.25_10regions_popgen_per_locus.gz \
H2_1.0_OPT_0.1_mu_0.005_sigmu0.25_10regions_popgen_per_locus.gz \
H2_1.0_OPT_0.5_mu_0.00025_sigmu0.25_10regions_popgen_per_locus.gz \
H2_1.0_OPT_0.5_mu_0.001_sigmu0.25_10regions_popgen_per_locus.gz \
H2_1.0_OPT_0.5_mu_0.005_sigmu0.25_10regions_popgen_per_locus.gz \
H2_1.0_OPT_1_mu_0.00025_sigmu0.25_10regions_popgen_per_locus.gz \
H2_1.0_OPT_1_mu_0.001_sigmu0.25_10regions_popgen_per_locus.gz \
H2_1.0_OPT_1_mu_0.005_sigmu0.25_10regions_popgen_per_locus.gz
	./combine_files.R -o combined_10locus_popgen_per_locus.gz H2*10regions_popgen_per_locus.gz
